import type { StatKey } from '../src/registry/stat-key.js';

export const SEED_STATS: readonly StatKey[] = [
  // ── DEFENSE ──
  {
    id: 'defense.life',
    displayName: 'Maximum Life',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.lifeIncreased',
    displayName: 'Increased Maximum Life',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'defense.energyShield',
    displayName: 'Maximum Energy Shield',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.energyShieldIncreased',
    displayName: 'Increased Maximum Energy Shield',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'defense.mana',
    displayName: 'Maximum Mana',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.armour',
    displayName: 'Armour',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.armourIncreased',
    displayName: 'Increased Armour',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'defense.evasion',
    displayName: 'Evasion Rating',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.evasionIncreased',
    displayName: 'Increased Evasion Rating',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'defense.ward',
    displayName: 'Ward',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.attackBlock',
    displayName: 'Attack Block Chance',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'defense.spellBlock',
    displayName: 'Spell Block Chance',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'defense.spellSuppression',
    displayName: 'Spell Suppression Chance',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 100,
  },
  {
    id: 'defense.lifeRegen',
    displayName: 'Life Regeneration per Second',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'defense.lifeRegenPercent',
    displayName: 'Life Regeneration Rate (%)',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'defense.manaRegen',
    displayName: 'Mana Regeneration per Second',
    category: 'defense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },

  // ── RESISTANCE ──
  {
    id: 'resistance.fire',
    displayName: 'Fire Resistance',
    category: 'resistance',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'resistance.cold',
    displayName: 'Cold Resistance',
    category: 'resistance',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'resistance.lightning',
    displayName: 'Lightning Resistance',
    category: 'resistance',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'resistance.chaos',
    displayName: 'Chaos Resistance',
    category: 'resistance',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },
  {
    id: 'resistance.maxFire',
    displayName: 'Maximum Fire Resistance',
    category: 'resistance',
    aggregation: { kind: 'maximum' },
    gameMappings: [],
    defaultBase: 75,
    isPercent: true,
  },
  {
    id: 'resistance.maxCold',
    displayName: 'Maximum Cold Resistance',
    category: 'resistance',
    aggregation: { kind: 'maximum' },
    gameMappings: [],
    defaultBase: 75,
    isPercent: true,
  },
  {
    id: 'resistance.maxLightning',
    displayName: 'Maximum Lightning Resistance',
    category: 'resistance',
    aggregation: { kind: 'maximum' },
    gameMappings: [],
    defaultBase: 75,
    isPercent: true,
  },
  {
    id: 'resistance.maxChaos',
    displayName: 'Maximum Chaos Resistance',
    category: 'resistance',
    aggregation: { kind: 'maximum' },
    gameMappings: [],
    defaultBase: 75,
    isPercent: true,
  },
  {
    id: 'resistance.allElemental',
    displayName: 'All Elemental Resistances',
    category: 'resistance',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
    defaultCap: 75,
  },

  // ── ATTRIBUTE ──
  {
    id: 'attribute.strength',
    displayName: 'Strength',
    category: 'attribute',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'attribute.dexterity',
    displayName: 'Dexterity',
    category: 'attribute',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'attribute.intelligence',
    displayName: 'Intelligence',
    category: 'attribute',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'attribute.allAttributes',
    displayName: 'All Attributes',
    category: 'attribute',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },

  // ── OFFENSE — DAMAGE ──
  {
    id: 'offense.physicalDamage',
    displayName: 'Physical Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'physical',
    defaultBase: 0,
  },
  {
    id: 'offense.fireDamage',
    displayName: 'Fire Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'fire',
    defaultBase: 0,
  },
  {
    id: 'offense.coldDamage',
    displayName: 'Cold Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'cold',
    defaultBase: 0,
  },
  {
    id: 'offense.lightningDamage',
    displayName: 'Lightning Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'lightning',
    defaultBase: 0,
  },
  {
    id: 'offense.chaosDamage',
    displayName: 'Chaos Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'chaos',
    defaultBase: 0,
  },
  {
    id: 'offense.elementalDamage',
    displayName: 'Elemental Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.elementalDamageWithAttacks',
    displayName: 'Elemental Damage with Attack Skills',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.spellDamage',
    displayName: 'Spell Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.genericDamage',
    displayName: 'Damage',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.dotMultiplier',
    displayName: 'Damage Over Time Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.fireDotMultiplier',
    displayName: 'Fire Damage Over Time Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.coldDotMultiplier',
    displayName: 'Cold Damage Over Time Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.physicalDotMultiplier',
    displayName: 'Physical Damage Over Time Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'offense.chaosDotMultiplier',
    displayName: 'Chaos Damage Over Time Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },

  // ── OFFENSE — SPEED ──
  {
    id: 'offense.attackSpeed',
    displayName: 'Attack Speed',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.castSpeed',
    displayName: 'Cast Speed',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.movementSpeed',
    displayName: 'Movement Speed',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.actionSpeed',
    displayName: 'Action Speed',
    category: 'offense',
    aggregation: { kind: 'product' },
    gameMappings: [],
    defaultBase: 1,
  },

  // ── OFFENSE — CRITICAL ──
  {
    id: 'offense.criticalChance',
    displayName: 'Critical Strike Chance',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.criticalMultiplier',
    displayName: 'Critical Strike Multiplier',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },

  // ── OFFENSE — PENETRATION ──
  {
    id: 'offense.firePenetration',
    displayName: 'Fire Penetration',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'fire',
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.coldPenetration',
    displayName: 'Cold Penetration',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'cold',
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.lightningPenetration',
    displayName: 'Lightning Penetration',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    damageType: 'lightning',
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'offense.elementalPenetration',
    displayName: 'Elemental Penetration',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },

  // ── OFFENSE — ACCURACY ──
  {
    id: 'offense.accuracy',
    displayName: 'Accuracy Rating',
    category: 'offense',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },

  // ── CONVERSION ──
  {
    id: 'conversion.physicalAsExtraFire',
    displayName: 'Physical Damage as Extra Fire Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalAsExtraCold',
    displayName: 'Physical Damage as Extra Cold Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalAsExtraLightning',
    displayName: 'Physical Damage as Extra Lightning Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalAsExtraChaos',
    displayName: 'Physical Damage as Extra Chaos Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalToFire',
    displayName: 'Physical Damage Converted to Fire Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalToCold',
    displayName: 'Physical Damage Converted to Cold Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'conversion.physicalToLightning',
    displayName: 'Physical Damage Converted to Lightning Damage',
    category: 'conversion',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },

  // ── RESOURCE ──
  {
    id: 'resource.lifeOnBlock',
    displayName: 'Life Gained on Block',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.lifeOnHit',
    displayName: 'Life Gained on Hit',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.lifeOnKill',
    displayName: 'Life Gained on Kill',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.manaOnBlock',
    displayName: 'Mana Gained on Block',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.manaOnHit',
    displayName: 'Mana Gained on Hit',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.manaOnKill',
    displayName: 'Mana Gained on Kill',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'resource.lifeLeech',
    displayName: 'Life Leech',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'resource.manaLeech',
    displayName: 'Mana Leech',
    category: 'resource',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },

  // ── SKILL ──
  {
    id: 'skill.areaOfEffect',
    displayName: 'Area of Effect',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.projectileCount',
    displayName: 'Additional Projectiles',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
  },
  {
    id: 'skill.projectileSpeed',
    displayName: 'Projectile Speed',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.skillDuration',
    displayName: 'Skill Effect Duration',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.cooldownRecovery',
    displayName: 'Cooldown Recovery Rate',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.trapThrowingSpeed',
    displayName: 'Trap Throwing Speed',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.mineThrowingSpeed',
    displayName: 'Mine Throwing Speed',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'skill.totemPlacementSpeed',
    displayName: 'Totem Placement Speed',
    category: 'skill',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },

  // ── AILMENT ──
  {
    id: 'ailment.bleedChance',
    displayName: 'Chance to Bleed',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
    defaultCap: 100,
  },
  {
    id: 'ailment.poisonChance',
    displayName: 'Chance to Poison',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
    defaultCap: 100,
  },
  {
    id: 'ailment.igniteChance',
    displayName: 'Chance to Ignite',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
    defaultCap: 100,
  },
  {
    id: 'ailment.shockEffect',
    displayName: 'Shock Effect',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'ailment.chillEffect',
    displayName: 'Chill Effect',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'ailment.ailmentDuration',
    displayName: 'Ailment Duration',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'ailment.ailmentEffect',
    displayName: 'Ailment Effect',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
  },
  {
    id: 'ailment.impaleChance',
    displayName: 'Chance to Impale',
    category: 'ailment',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    isPercent: true,
    defaultBase: 0,
    defaultCap: 100,
  },

  // ── MECHANIC ──
  {
    id: 'mechanic.keystone_ci',
    displayName: 'Chaos Inoculation',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.immuneChaos',
    displayName: 'Immune to Chaos Damage',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_eb',
    displayName: 'Eldritch Battery',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_mom',
    displayName: 'Mind over Matter',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_ironReflexes',
    displayName: 'Iron Reflexes',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_ironGrip',
    displayName: 'Iron Grip',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_resoluteTechnique',
    displayName: 'Resolute Technique',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_zealotsOath',
    displayName: "Zealot's Oath",
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_ghostReaver',
    displayName: 'Ghost Reaver',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_ancestralBond',
    displayName: 'Ancestral Bond',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_bloodMagic',
    displayName: 'Blood Magic',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_painAttunement',
    displayName: 'Pain Attunement',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_acrobatics',
    displayName: 'Acrobatics',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_glancingBlows',
    displayName: 'Glancing Blows',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },
  {
    id: 'mechanic.keystone_divineShield',
    displayName: 'Divine Shield',
    category: 'mechanic',
    aggregation: { kind: 'flag' },
    gameMappings: [],
  },

  // ── ENEMY ──
  {
    id: 'enemy.fireResistance',
    displayName: 'Enemy Fire Resistance',
    category: 'enemy',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'enemy.coldResistance',
    displayName: 'Enemy Cold Resistance',
    category: 'enemy',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'enemy.lightningResistance',
    displayName: 'Enemy Lightning Resistance',
    category: 'enemy',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'enemy.chaosResistance',
    displayName: 'Enemy Chaos Resistance',
    category: 'enemy',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'enemy.physicalResistance',
    displayName: 'Enemy Physical Damage Reduction',
    category: 'enemy',
    aggregation: { kind: 'sum' },
    gameMappings: [],
    defaultBase: 0,
    isPercent: true,
  },
  {
    id: 'enemy.damageTaken',
    displayName: 'Enemy Damage Taken',
    category: 'enemy',
    aggregation: { kind: 'product' },
    gameMappings: [],
    defaultBase: 1,
  },
] as const;
