export type { HttpClient, HttpOptions } from './http/index.js';
export { FetchHttpClient, MockHttpClient } from './http/index.js';

export {
  isPobPastebinUrl,
  isPobbUrl,
  isPoBUrl,
  extractPastebinId,
  parsePobXml,
  parsePobPastebin,
  importFromPobUrl,
  importFromPobXml,
  convertPobDto,
  convertPobItems,
  parseLifeMod,
  parseResistanceMod,
  parseFlatDamageMod,
  parseIncreasedDamageMod,
  parseEnergyShieldMod,
  DAMAGE_STAT_MAP,
  RESISTANCE_STAT_MAP,
} from './pob/index.js';

export type {
  PoBBuildAttributes,
  PoBSkill,
  PoBSkillSet,
  PoBMod,
  PoBSocket,
  PoBItem,
  PoBTree,
  PoBConfig,
  PoBXmlDTO,
  PoBImportOptions,
} from './pob/index.js';

export {
  createNinjaSource,
  createTradeSource,
  createWikiSource,
  createForumSource,
  createItemLoader,
  createSkillLoader,
  createPassiveLoader,
  createLeagueLoader,
  normalizeItem,
  normalizeItems,
  normalizeSkill,
  normalizeSkills,
  normalizeMod,
  normalizeMods,
  normalizeEconomyEntry,
  normalizeEconomyEntries,
  normalizeLeague,
  normalizeLeagues,
  runSyncPipeline,
  SyncScheduler,
  createSyncResult,
} from './data/index.js';

export type {
  DataSource,
  DataSourceOptions,
  NinjaSource,
  TradeSource,
  TradeSearchResult,
  WikiSource,
  ForumSource,
  ForumThread,
  ItemLoaderResult,
  SkillLoaderResult,
  PassiveTreeInfo,
  LeagueLoaderResult,
  SyncEngineOptions,
  SyncSchedulerOptions,
  SyncResult,
} from './data/index.js';

export {
  fromPob,
  resolveBuildStats,
  resolveItemStats,
  aggregateMods,
  estimateOffense,
  calculateDefense,
  evaluateDamageReport,
  evaluateDefenseReport,
  evaluateScaling,
  detectUpgrades,
  analyze,
  explainProblem,
  explainRecommendation,
  buildRecommendationList,
  parsePobXml as parsePobXmlLegacy,
  parsePobPastebin as parsePobPastebinLegacy,
  isPobPastebinUrl as isPobPastebinUrlLegacy,
  extractPastebinId as extractPastebinIdLegacy,
  importFromPobUrl as importFromPobUrlLegacy,
  importFromPobXml as importFromPobXmlLegacy,
} from './legacy/index.js';

export type {
  ProblemExplanation,
  Build,
  EquipmentSlot,
  EquippedItem,
  Modifier,
  ComputedItemStats,
  CharacterBase,
  PassiveTreeSnapshot,
  SkillSetup,
  SkillGem,
  BuildConfig,
  AnalysisResult,
  AnalysisContext,
  OffenseReport,
  DefenseReport,
  Problem,
  Warning,
  UpgradeRecommendation,
  ScalingReport,
  BuildScores,
  BuildSummary,
  AnalysisMetadata,
  SocketGroup,
  DamageRange,
  ItemRarity,
  SkillSummary,
  LeechSummary,
  GuardSkillSummary,
  DamageProfile,
  ScalingVector,
  ChargeState,
  ClusterJewelSummary,
  Influence,
  PoBXmlDTO as PoBXmlDTOLegacy,
  PoBBuildAttributes as PoBBuildAttributesLegacy,
  PoBSkill as PoBSkillLegacy,
  PoBSkillSet as PoBSkillSetLegacy,
  PoBMod as PoBModLegacy,
  PoBSocket as PoBSocketLegacy,
  PoBItem as PoBItemLegacy,
  PoBTree as PoBTreeLegacy,
  PoBConfig as PoBConfigLegacy,
  PoBImportOptions as PoBImportOptionsLegacy,
} from './legacy/index.js';

export {
  createAIProvider,
  createOpenAIProvider,
  createAnthropicProvider,
  createOpenRouterProvider,
  createLMStudioProvider,
} from './ai/index.js';

export type {
  AIProviderConfig,
  OpenAIProviderConfig,
  AnthropicProviderConfig,
  OpenRouterProviderConfig,
  LMStudioProviderConfig,
} from './ai/index.js';
